/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgentRegistry__factory } from "./AgentRegistry__factory";
export { AgentRegistryOLD__factory } from "./AgentRegistryOLD__factory";
export { ConsumerRegistry__factory } from "./ConsumerRegistry__factory";
